# General application settings
app:
  s3:
    bucket-name: "message-bucket" # Used by the local profile

# Spring Cloud AWS specific settings
spring:
  cloud:
    aws:
      region:
        static: sa-east-1
      credentials:
        # This tells the SDK to look for credentials automatically (e.g., from ~/.aws/credentials)
        use-default-chain: true
  # Set the default active profile to local for easier development
  profiles:
    active: local

---
# Settings specific to the 'local' profile
spring:
  config:
    activate:
      on-profile: local
  cloud:
    aws:
      s3:
        # This endpoint setting is ONLY used when the 'local' profile is active.
        # It redirects all S3 calls to our LocalStack container.
        endpoint: http://localhost:4566
        # This is required for LocalStack to work correctly with the AWS SDK v2
        path-style-access-enabled: true

---
# Settings specific to the 'production' profile
spring:
  config:
    activate:
      on-profile: production
# Production profile settings can be added here in the future.
# For now, it relies on environment variables provided by AWS ECS.

